# Generated by Django 3.1.1 on 2020-09-26 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domicilio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('apellido_cliente', models.CharField(max_length=100)),
                ('telefono', models.PositiveIntegerField(validators=[django.core.validators.RegexValidator('^\\d{8,8}$')])),
                ('direccion', models.TextField()),
            ],
        ),
    ]
