# Generated by Django 3.1.1 on 2020-09-26 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domicilio', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('hora_orden', models.TimeField()),
                ('detalle', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domicilio.cliente')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domicilio.usuario')),
            ],
        ),
    ]
